CREATE DATABASE IF NOT EXISTS cafe_satu_nusa CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE cafe_satu_nusa;

CREATE TABLE users(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(120) NOT NULL,
 username VARCHAR(80) UNIQUE NOT NULL,
 password_hash VARCHAR(255) NOT NULL,
 role ENUM('OWNER','ADMIN','KASIR','KITCHEN') NOT NULL DEFAULT 'KASIR',
 active TINYINT(1) NOT NULL DEFAULT 1,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categories(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) UNIQUE NOT NULL,active TINYINT(1) DEFAULT 1);
CREATE TABLE menus(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(160) NOT NULL,category_id BIGINT UNSIGNED NULL,price BIGINT NOT NULL DEFAULT 0,description TEXT,active TINYINT(1) DEFAULT 1,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE stock(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(160) NOT NULL,qty DECIMAL(14,3) NOT NULL DEFAULT 0,unit VARCHAR(30) NOT NULL,min_qty DECIMAL(14,3) NOT NULL DEFAULT 0,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE recipes(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,menu_id BIGINT UNSIGNED NOT NULL,stock_id BIGINT UNSIGNED NOT NULL,qty DECIMAL(14,4) NOT NULL);
CREATE TABLE customers(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(160) NOT NULL,phone VARCHAR(40),points BIGINT NOT NULL DEFAULT 0,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE orders(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,local_id BIGINT NULL,table_no VARCHAR(50),subtotal BIGINT NOT NULL,total BIGINT NOT NULL,payment VARCHAR(30),status VARCHAR(30),discount BIGINT DEFAULT 0,tax BIGINT DEFAULT 0,service BIGINT DEFAULT 0,customer_id BIGINT NULL,notes TEXT,created_at DATETIME NOT NULL,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE order_items(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,order_id BIGINT UNSIGNED NOT NULL,menu_id BIGINT UNSIGNED NULL,menu_name VARCHAR(160),qty INT NOT NULL,price BIGINT NOT NULL,note TEXT);
CREATE TABLE expenses(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(180) NOT NULL,amount BIGINT NOT NULL,category VARCHAR(80),created_at DATETIME NOT NULL);
CREATE TABLE sync_logs(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,device_id VARCHAR(120),entity_name VARCHAR(80),entity_id BIGINT,action VARCHAR(30),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

INSERT INTO users(name,username,password_hash,role) VALUES('Owner','owner','$2y$10$REPLACE_WITH_PASSWORD_HASH','OWNER');
